<a href="https://colab.research.google.com/github/PaulToronto/DataCamp-Track---Machine-Learning-Scientist-in-Python/blob/main/5_1_Linear_Classifiers_in_Python_Applying_Logistic_Regression_and_SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 5-1 Linear Classifiers in Python - Applying Logistic Regression and SVM.

## Imports

In [1]:
import pandas as pd
import numpy as np

import sklearn.datasets as datasets
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

## scikit-learn refresher

### Supervised Learning Steps

#### Get the data

In the newgroups data
- The features are derived from the words appearing in each article
- The y values are the article topics, which is what we're trying to predi t

In [2]:
newsgroups = datasets.fetch_20newsgroups_vectorized()

In [3]:
type(newsgroups)

sklearn.utils._bunch.Bunch

In [4]:
X, y = newsgroups.data, newsgroups.target

In [5]:
X.shape, y.shape

((11314, 130107), (11314,))

In [6]:
print(len(newsgroups.feature_names))
newsgroups.feature_names

130107


array(['00', '000', '0000', ..., 'íålittin', 'ñaustin', 'ýé'],
      dtype=object)

In [7]:
print(len(newsgroups.target_names))
newsgroups.target_names

20


['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [8]:
print(len(np.unique(y)))
np.unique(y, return_counts=True)

20


(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19]),
 array([480, 584, 591, 590, 578, 593, 585, 594, 598, 597, 600, 595, 591,
        594, 593, 599, 546, 564, 465, 377]))

#### Fitting and predicting

In [9]:
knn = KNeighborsClassifier(n_neighbors=1)
knn

KNeighborsClassifier(n_neighbors=1)

In [10]:
knn.fit(X, y)

KNeighborsClassifier(n_neighbors=1)

In [11]:
y_pred = knn.predict(X)
y_pred

array([17,  7, 10, ..., 14, 12, 11])

#### Model evaluation

In [12]:
knn.score(X, y)

0.9999116139296447

In [13]:
# manually
sum(y_pred == y) / len(y)

0.9999116139296447

- This accuracy score is not very meaningful because we want to know how well the model generalizes to unseen data

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((8485, 130107), (2829, 130107), (8485,), (2829,))

In [15]:
knn = KNeighborsClassifier(n_neighbors=1)

knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [16]:
# test score
knn.score(X_test, y_test)

0.6726758571933545

- The model does not do as well when predicting previously unseen data

In [17]:
knn_test = KNeighborsClassifier(n_neighbors=1)
knn_test

KNeighborsClassifier(n_neighbors=1)

## Applying logistic regression and SVM